name: Check linting and formatting of the backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting_and_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Formatting
        run: npm run format

      - name: Check for changes
        run: git diff --exit-code